build_targets:
- commands:
  - dpkg --add-architecture i386
  - apt-get update 
  - apt-get install -y make ant zip libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386
  - make circleci
  container:
    image: yourbase/yb_ubuntu:16.04
  name: default

ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:8.232.09
